Default: &defaults
  database: Sudoku.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Sudoku_test.sqlite3
  <<: *defaults

Staging:
  database: Sudoku_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Sudoku_production.sqlite3
  poolsize: 100
  <<: *defaults
